### ISSUE TITLE
CONTRIBUTING.md outdated link

### ISSUE THREAD

**Issue by Gaitz** [sss63232/CopyUrlToMD#8]
* CONTRIBUTING.md outdated link
  https://github.com/sss63232/CopyUrlToMD/blame/master/CONTRIBUTING.md#L36

  link to https://code.likeagirl.io/useful-tips-for-writing-better-git-commit-messages-808770609503 get 410.

Would you like to add https://www.conventionalcommits.org/ as commit reference ?

**Comment by sss63232** [comment]
Yeah! sure. 

Beside updating the doc, could you also help add the badge to the repo.
See [conventional-commits/conventionalcommits.org: The conventional commits specification](https://github.com/conventional-commits/conventionalcommits.org#badges)
